#!/usr/bin/env bash
#Create script that tell the story of passwd
while IFS= read -r line
do
	echo -n "The user $username is part of the $groupID gang, "
	echo -n "lives in $home and rides $command. "
	echo -n "$userID's place is protected by the passcode $password, "
	echo -n "more info about the user here: $userINFO"
done <"/etc/passwd"
