#!/usr/bin/env bash
#Create script that tell the story of passwd
while IFS= read -r line
do
	username=$(echo "$line" | cut -f 1 -d ':')
	password=$(echo "$line" | cut -f 2 -d ':')
	userID=$(echo "$line" | cut -f 3 -d ':')
	groupID=$(echo "$line" | cut -f 4 -d ':')
	userINFO=$(echo "$line" |cut -f 5 -d ':')
	home=$(echo "$line" | cut -f 6 -d ':')
	command=$(echo "$line" | cut -f 7 -d ':')


	echo -n "The user USERNAME is part of the GROUP_ID gang, "
	echo -n "lives in HOME_DIRECTORY and rides COMMAND/SHELL. "
	echo -n "USER ID's place is protected by the passcode PASSWORD, "
	echo "more info about the user here: USER ID INFO"
done <"/etc/passwd"
