#!/usr/bin/env bash
#Create a script that displays the time for 12 hours and 59 minutes
Hour=0
while [ $Hour -le 12 ]
do
echo '$Hour'
minutes=1
while [ $minutes -lt 60 ]
do
echo '$minutes'
((minutes++))
done
((hour++))
done
