#!/usr/bin/env bash
#Create a script that displays the time for 12 hours and 59 minutes
hour=1
while [ $hour -le 12 ]
do
echo 'Hour: $hour'
minutes=1
while [ $minutes -lt 60 ]
do
echo '$minutes'
((minutes++))
done
((Hour++))
done | head -n 70
