#!/usr/bin/env bash
#Create a script that show process and PID file
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
trap 'rm -rf /var/run/myscript.pid; exit' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 4
done
