#!/usr/bin/env bash
#Create a script that Manage my process

PID=/var/run/my_process.pid

start() {
	./manage_my_process &
	echo "$!" > "$PID"
}

stop() {
	sudo kill -15 "$(cat "$PID")" && rm -f "$PID"
}

case "$1" in 
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
